### ISSUE TITLE
No reaction to the key [ENTER] or [RETURN] on entering a search term

### ISSUE THREAD

**Issue by Tom-0169** [Metal-spoon/win95-newtab#41]
Could you integrate, that the search is started when you hit [ENTER] or [RETURN] ?

**Comment by Metal-spoon** [comment]
This should work, I'll investigate when I get home from holidays.

In the meantime, what browser are you using and which version of the extension are you using?

**Comment by Tom-0169** [comment]
I'm using Chrome with the latest extension from the web store.
Which is version 1.08.
Thanks for considering this.

**Comment by Metal-spoon** [comment]
Can't seem to replicate this, it works whenever you press enter when you are focused on the text input.
Unless you are expecting different behavior? If so, what would you like to see?

**Comment by Tom-0169** [comment]
Hmm, don't know what was wrong with my chrome on the last days.
Today it works....

**Comment by Tom-0169** [comment]
The [RETURN] key works, but not the [ENTER] key on the numpad section.

**Comment by Metal-spoon** [comment]
> The [RETURN] key works, but not the [ENTER] key on the numpad section.

Got it, will add tonight :)

**Comment by Metal-spoon** [comment]
Pushed a possible fix to the issue41 branch. 
Needs testing as i don't have a keyboard with numpad at hand until later today.

**Comment by Metal-spoon** [comment]
Tested it, numpad enter works now :)
Merged it with develop and will push to the firefox/chrome stores today.

**Comment by Tom-0169** [comment]
Just tested version 1.0.9 in Chrome and it does NOT function.

**Comment by Metal-spoon** [comment]
> Just tested version 1.0.9 in Chrome and it does NOT function.

It wasn't pushed to the stores yet, 1.0.10 should fix this issue.
They're pending review as of writing this, could take a few days but that's on google.

**Comment by Tom-0169** [comment]
Ah ok, thanks for the work !
