### ISSUE TITLE
Wallpapers sometimes do not save

### ISSUE THREAD

**Issue by Metal-spoon** [Metal-spoon/win95-newtab#5]
Wallpapers sometimes do not save.
More information is needed, if you encounter this issue please attach the file you are trying to upload.

**Comment by Metal-spoon** [comment]
Possibly related to the file input, might not be clearing correctly.

**Comment by W1nKille3r** [comment]
![2](https://user-images.githubusercontent.com/68503107/180821954-ee0e6243-696e-42fb-b7e6-34a553459d99.png)
![3](https://user-images.githubusercontent.com/68503107/180821959-089a50c7-14fd-4fa0-9b3f-d81a095f64e3.png)
![4](https://user-images.githubusercontent.com/68503107/180821966-e822e2f9-90d5-4890-9426-84200f095ab2.png)
![5](https://user-images.githubusercontent.com/68503107/180821971-b71a27a4-cd0e-46f4-9a75-ff9eada6a172.png)
![6](https://user-images.githubusercontent.com/68503107/180821976-01783115-c445-4aa5-91d5-c7ef8fb4f282.png)
![7](https://user-images.githubusercontent.com/68503107/180821979-fb576d98-b2cc-463b-9dfa-9c0e077e2e98.png)
![8](https://user-images.githubusercontent.com/68503107/180821981-d4d62b52-4238-4525-a4f3-b8c8b5279588.png)
![9](https://user-images.githubusercontent.com/68503107/180821985-d78739bc-e90c-41f3-8915-4ae8c5e1324f.png)
![10](https://user-images.githubusercontent.com/68503107/180821989-5285e6a2-38dd-43b6-b911-6b749d162aad.png)
![11](https://user-images.githubusercontent.com/68503107/180821993-c9529692-d807-470d-8242-e744af076f54.png)

**Comment by W1nKille3r** [comment]
In general - i tried somehow reconvert them due Photoshop. From JPG to PNG. Anyways many photos still doesn't save into add-on.

**Comment by W1nKille3r** [comment]
Also tried to resize them from 4K to the same FHD. Don't work anyways

**Comment by W1nKille3r** [comment]
Only working these two.
![Screenshot_1](https://user-images.githubusercontent.com/68503107/180822442-8a064b42-6932-465b-a4f9-b6fc72d351aa.png)

**Comment by W1nKille3r** [comment]
Isn't size related.

**Comment by W1nKille3r** [comment]
Doing worse JPG Compression fixes save issue. But some images gonna be look crappy.
![523](https://user-images.githubusercontent.com/68503107/180825267-9d44599d-1437-4e2d-8a6a-8d77525c5a78.jpg)

**Comment by Metal-spoon** [comment]
Thanks a lot for the information @W1nKille3r, will be testing with them this week to see if i can reproduce it!

**Comment by Metal-spoon** [comment]
Issue is being caused by wallpapers being saved in localstorage and exceeding localstorage limits.
Solution is to either find a different way to save/load wallpapers or to limit the amount of wallpapers that can be uploaded according to size.

**Comment by Metal-spoon** [comment]
Should be fixed with #15 
Performance is still lacking, will try to optimize before next release.
Also necessitates refactoring other components that use localstorage, everything should use the same storage that is used for wallpapers.

Thanks again @W1nKille3r for the data :+1:
